### ISSUE TITLE
Add --password CLI Parameter

### ISSUE THREAD

**Issue by ChandlerFerry** [Xenophyte-coin/Xenophyte-RPC-Wallet#2]
Problem:
> When starting the RPC Wallet, it prompts a password. This is a problem because when running in a Docker container, it is difficult to recovery automatically from crashes when manual inputs are required.

Solution:
> Add --password CLI Parameter that bypasses the manual input requirement

**Comment by Xenophyte-coin** [comment]
Already exist by: `--rpc-password=`

https://github.com/Xenophyte-coin/Xenophyte-RPC-Wallet/wiki/Argument-of-the-RPC-Wallet
